version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
    - "6379:6379"
    env_file:
      - ./.env
    command: redis-server --bind 0.0.0.0 --requirepass spimex_cache_password --appendonly yes
    restart: unless-stopped
